use super::Syntax;
use std::collections::BTreeSet;

impl Syntax {
    pub fn wgsl() -> Self {
        Syntax {
            language: "Wgsl",
            case_sensitive: true,
            comment: "//",
            comment_multiline: ["/*", "*/"],
            hyperlinks: BTreeSet::from(["http"]),
            keywords: BTreeSet::from([
                "@align",
                "@binding",
                "@builtin",
                "@compute",
                "@const",
                "@diagnostic",
                "@fragment",
                "@group",
                "@id",
                "@include",
                "@interpolate",
                "@invariant",
                "@location",
                "@blend_src",
                "@must_use",
                "@size",
                "@vertex",
                "@workgroup_size",
                "alias",
                "break",
                "case",
                "const",
                "const_assert",
                "continue",
                "continuing",
                "default",
                "diagnostic",
                "discard",
                "else",
                "enable",
                "fn",
                "for",
                "if",
                "let",
                "loop",
                "override",
                "requires",
                "return",
                "struct",
                "switch",
                "var",
                "while",
            ]),
            types: BTreeSet::from([
                "atomic", "array", "bool", "i32", "u32", "f16", "f32", "vec2", "vec2i", "vec2f",
                "vec2h", "vec3", "vec3i", "vec3f", "vec3h", "vec4", "vec4i", "vec4f", "vec4h",
                "mat2x2", "mat2x2f", "mat2x2h", "mat2x3", "mat2x3f", "mat2x3h", "mat2x4",
                "mat2x4f", "mat2x4h", "mat3x2", "mat3x2f", "mat3x2h", "mat3x3", "mat3x3f",
                "mat3x3h", "mat3x4", "mat3x4f", "mat3x4h", "mat4x2", "mat4x2f", "mat4x2h",
                "mat4x3", "mat4x3f", "mat4x3h", "mat4x4", "mat4x4f", "mat4x4h",
            ]),
            special: BTreeSet::from(["true", "false"]),
        }
    }
}
